#!/bin/sh

# $Id: install-gcc-wrapper,v 1.5 2004-02-05 18:24:06-08 kst Exp $
# $Source: /home/kst/CVS_smov/tools/gcc-wrapper/install-gcc-wrapper,v $

########################################################################
# @Copyright@
#
# Copyright (c) 2004 The Regents of the University of California. All
# rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# 3. All advertising materials mentioning features or use of this
# software must display the following acknowledgement: This product
# includes software developed by the Grid and Cluster Computing Group
# at the San Diego Supercomputer Center and its contributors.
#
# 4. Neither the name of the Center nor the names of its contributors
# may be used to endorse or promote products derived from this software
# without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# @Copyright@
########################################################################

########################################################################
# Installation script for gcc-wrapper release 0.1
########################################################################

########################################################################
# Developed by Keith Thompson <kst@sdsc.edu>
########################################################################

usage() {
    cat <<"EOF"
Usage: $0 [options] install-dir
install-dir may not be an existing directory; it will be created.
    -help      Display this message and exit
    -gcc cmd   Full path of gcc executable; default is searched in $PATH
               gcc version must be 3.2.
    -force     Disable check for gcc version 3.2
               Disable check that specified gcc command is named "gcc"
EOF
    exit 1
}

try() {
    echo "% $@"
    $@ || die "Command failed"
}

die() {
    echo ">>> $@" 1>&2
    exit 1
}

unset install_dir
unset gcc_location
force=0

while [ $# -ne 0 ] ; do
    case "$1" in
        -help)
            usage
            ;;
        -gcc)
            shift
            if [ $# -eq 0 ] ; then
                echo "-gcc option requires an argument" 1>&2
                usage
            fi
            gcc_location=$1
            ;;
        -force)
            force=1
            ;;
        -*)
            echo "Unrecognized option \"$1\"" 1>&2
            usage
            ;;
        /*)
            if [ "$install_dir" != "" ] ; then
                echo "install-dir already specified" 1>&2
                usage
            fi
            install_dir=$1
            ;;
        *)
            echo "Unrecognized argument \"$1\"" 1>&2
            usage
            ;;
    esac
    shift
done

if [ ! -f gcc-wrapper ] ; then
    echo "No gcc-wrapper in current directory" 1>&2
    usage
fi
if [ ! -f README ] ; then
    echo "No README file in current directory" 1>&2
    usage
fi

if [ "$install_dir" = "" ] ; then
    echo "No installation directory specified" 1>&2
    usage
fi

if [ -d "$install_dir" ] ; then
    echo "Installation directory $install_dir already exists" 1>&2
    usage
fi

if [ "$gcc_location" = "" ] ; then
    for dir in `echo $PATH | tr : ' '` ; do
        if [ -x "$dir/gcc" ] ; then
            gcc_location="$dir/gcc"
            break
        fi
    done
fi

if [ "$gcc_location" = "" ] ; then
    echo "No gcc found or specified" 1>&2
    usage
fi

if [ "`basename $gcc_location`" != "gcc" ] ; then
    if [ $force = 1 ] ; then
        echo "Warning: $gcc_location is not named \"gcc\"" 1>&2
    else
        echo "$gcc_location is not named \"gcc\"" 1>&2
        usage
    fi
fi

gcc_version=`$gcc_location --version | awk 'NR==1{print $3}'`
if [ "$gcc_version" != "3.2" ] ; then
    if [ $force = 1 ] ; then
        echo "Warning: gcc version is $gcc_version, expected 3.2" 1>&2
    else
        echo "gcc version is $gcc_version, expected 3.2" 1>&2
        usage
    fi
fi

try mkdir $install_dir
try mkdir $install_dir/bin
try cp -p gcc-wrapper $install_dir/bin/gcc-wrapper
try cp -p README $install_dir/README
cd $install_dir/bin || die "cd failed"
try ln -s gcc-wrapper gcc
try ln -s $gcc_location gcc.real

echo ''
echo "===== See $install_dir/README ====="
